# Project information
site_name: Geotribu
site_description: >-
  Site indépendant de veille sur la géomatique libre et open source.
  Articles, tutoriels et revues de presse (#GeoRDP) sur
  l'information géographique, les SIG, la cartographie, la représentation des données...

site_author: Geotribu
site_url: https://static.geotribu.fr/
copyright: '<span class="copyleft">&copy;</span> Geotribu'

# Repository
repo_name: !ENV [GITHUB_REPOSITORY, "geotribu/website"]
repo_url: !ENV [MKDOCS_REPO_URL, "https://github.com/geotribu/website"]
edit_uri: !ENV [MKDOCS_EDIT_URI, "edit/master/content"]

# Custom folder structure
docs_dir: "./content"
site_dir: "./build/mkdocs/site"

# Plugins
plugins:
  - awesome-pages
  - exclude:
      glob:
        - "*/templates/*"
        - "*.yml"
  - git-authors:
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_GIT_AUTHORS, False]
      exclude:
        - index.md
      show_contribution: true
  - git-revision-date-localized:
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_GIT_DATES, False]
      enable_creation_date: true
      fallback_to_build_date: true
      locale: fr
  - minify:
      minify_css: true
      minify_html: true
      minify_js: false
      htmlmin_opts:
        remove_comments: true
  - rss:
      abstract_chars_count: 500
      categories:
        - categories
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d %H:%M"
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_RSS, false]
      image: "https://cdn.geotribu.fr/img/internal/charte/geotribu_logo_64x64.png"
      length: 50
      match_path: "(articles|rdp)/.*"
      pretty_print: true
      url_parameters:
        utm_source: "rss-feed"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
  - search:
      lang: fr
  - macros:
      include_dir: content/toc_nav_ignored/snippets
  - tags:
      tags_file: tags.md
  - privacy:
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_PRIVACY, false]
      externals_exclude:
        # geotribu
        - cdn.geotribu.fr/images/*
        - cdn.geotribu.fr/img/*
        - geotribu.net/*
        - www.geotribu.net/*
        - ks356007.kimsufi.com/*
        # external
        - github.com/**/*.gif
        - i.imgur.com/*
        - raw.githubusercontent.com/*
        - twemoji.maxcdn.com/*
        - upload.wikimedia.org/*
        - user-images.githubusercontent.com/**/*.gif
        # to remove later:
        - dev.openstreetmap.org/*
        - www.portailsig.org/assets/images/*
        - 88.191.39.115/*
        - cdn.theatlanticcities.com/img/*
        - boundlessgeo.com/*
        - i3.codeplex.com/*
        - drfhlmcehrc34.cloudfront.net/*

# Theme
theme:
  name: "material"
  custom_dir: "./content/theme/"
  favicon: "https://cdn.geotribu.fr/img/internal/charte/geotribu_logo_64x64.png"

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font: false
  icon:
    repo: fontawesome/brands/github-alt
    tag:
      default: fontawesome/solid/tag
      # -- custom tags icons
      ananas: material/fruit-pineapple
      atlas: fontawesome/solid/book-atlas
      brick: material/toy-brick
      cerveau: material/brain
      citrouille: material/pumpkin
      code: fontawesome/solid/code
      commentaires: fontawesome/solid/comments
      conference: fontawesome/solid/person-chalkboard
      database: fontawesome/solid/database
      facebook: fontawesome/brands/facebook
      feuille: fontawesome/solid/leaf
      geoloupe: fontawesome/solid/magnifying-glass-location
      git: fontawesome/brands/git-alt
      globe: fontawesome/solid/earth-europe
      google: fontawesome/brands/google
      html: fontawesome/brands/html5
      institution: fontawesome/solid/building-columns
      js: fontawesome/brands/js
      manette: fontawesome/solid/gamepad
      markdown: fontawesome/brands/markdown
      masques: fontawesome/solid/masks-theater
      meridiens: fontawesome/solid/globe
      oeuf: fontawesome/solid/egg
      open: fontawesome/solid/lock-open
      opensource: material/open-source-initiative
      python: fontawesome/brands/python
      roue: material/cog-play
      route: fontawesome/solid/route
      rstats: fontawesome/brands/r-project
      satellite: fontawesome/solid/satellite-dish
      streetview: fontawesome/solid/street-view
      telephone: material/cellphone-marker
      windows: fontawesome/brands/windows
  language: fr
  logo: "https://cdn.geotribu.fr/img/internal/charte/geotribu_logo_64x64.png"
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Basculer en mode clair

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: "deep orange"
      toggle:
        icon: material/weather-sunny
        name: Basculer en mode sombre

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: "deep orange"
      toggle:
        icon: material/weather-night
        name: Basculer sur le réglage système

# Customization
extra:
  analytics:
    provider: google
    property: !ENV MKDOCS_GOOGLE_ANALYTICS_KEY
  comments_url: https://comments.geotribu.fr # isso url
  consent:
    title: Consentement 🍪
    actions:
      - accept
      - manage
      - reject
    description: >
      Nous utilisons des cookies pour le goûter mais aussi pour vous proposer
      des fonctionnalités (commentaires, thème clair ou sombre, etc.) et mesurer
      l'audience du site.
  social:
    - icon: "fontawesome/solid/rss"
      link: "https://static.geotribu.fr/feed_rss_created.xml"
      name: "S'abonner aux nouveaux contenus via RSS"
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/geotribu/"
      name: "L'organisation Github de Geotribu"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/geotribu"
      name: "Geotribu sur Twitter"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/feed/hashtag/?keywords=geotribu"
      name: "Les contenus de Geotribu sur LinkedIn"
    - icon: "fontawesome/brands/youtube"
      link: "https://www.youtube.com/channel/UCfpO6BcaqxxykBOWJzP_9jg/"
      name: "Chaîne Youtube de Geotribu"
    - icon: "fontawesome/brands/facebook"
      link: "https://fr-fr.facebook.com/geotribu/"
      name: "Page Facebook de Geotribu"
    - icon: "fontawesome/brands/mailchimp"
      link: http://eepurl.com/hL0zVr
      name: "Abonnez-vous à la newsletter"
    - icon: fontawesome/solid/paper-plane
      link: mailto:<geotribu@gmail.com>
      name: "Nous contacter"
    - icon: "fontawesome/brands/slack"
      link: "https://geotribu.slack.com"
      name: "Rejoignez-nous sur Slack"
    - icon: "fontawesome/solid/feather-pointed"
      link: http://pad.geotribu.fr/
      name: "Editeur en ligne"
    - icon: "fontawesome/solid/piggy-bank"
      link: https://fr.tipeee.com/geotribu/
      name: "Le pot commun sur Tipee"
  tags:
    atlas: atlas
    Bash: code
    Centipede: satellite
    CNIG: institution
    collecte: telephone
    collecte terrain: telephone
    coulisses: masques
    cURL: code
    D3.js: js
    Easter eggs: oeuf
    Esri: globe
    ETL: roue
    ExtJS: js
    Facebook: facebook
    FIG: conference
    FME: roue
    FOSS4G: conference
    GéoDataDays: conference
    GeoGames: manette
    GeoKettle: roue
    géo-lecture: atlas
    Git: git
    GitHub: git
    GitLab: git
    Google: google
    Google Earth: google
    Google Maps: google
    Google Street View: google
    GraphHopper: route
    Halloween: citrouille
    HTML: html
    HTML5: html
    IA: cerveau
    IGN: institution
    Input: telephone
    INSPIRE: ananas
    IRC: commentaires
    JavaScript: js
    jeu: manette
    jeux vidéo: manette
    Leaflet: feuille
    Lego: brick
    LIDAR: satellite
    livre: atlas
    Mapillary: streetview
    Markdown: markdown
    Matrix: commentaires
    Minecraft: manette
    MySQL: database
    ODK: telephone
    Open Data Kit: telephone
    OpenPathView: streetview
    OpenRouteService: route
    open data: open
    open source: opensource
    OpenStreetMap: geoloupe
    OSRM: route
    Open Earth View: streetview
    pgDay: database
    pgRouting: route
    PGSession: database
    PostGIS: database
    PostgreSQL: database
    projection: meridiens
    PyCSW: python
    PyGEOS: python
    PyQGIS: python
    PyQt: python
    PySQL: python
    Python: python
    PyWPS: python
    QField: telephone
    QGIS: globe
    R: rstats
    route: route
    routing: route
    SQL: database
    three.js: js
    Windows: windows

extra_css:
  - "theme/assets/stylesheets/extra.css"
  - "https://cdn.jsdelivr.net/npm/wa-mediabox@1.0.1/dist/wa-mediabox.min.css"

extra_javascript:
  - "theme/assets/javascripts/extra.js"
  - "https://cdn.jsdelivr.net/npm/wa-mediabox@1.0.1/dist/wa-mediabox.min.js"

# Extensions to enhance markdown - see: https://squidfunk.github.io/mkdocs-material/getting-started/#extensions
markdown_extensions:
  - abbr
  # Admonition - https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition
  - attr_list
  # Footnotes - https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes
  - md_in_html
  # Metadata - https://squidfunk.github.io/mkdocs-material/extensions/metadata
  - meta
  # PyMdown extensions - https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.saneheaders
  # https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  - pymdownx.snippets:
      auto_append: [content/toc_nav_ignored/snippets/glossaire.md]
      base_path: "."
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  # Permalinks - https://squidfunk.github.io/mkdocs-material/extensions/permalinks/
  - toc:
      permalink: "#"
